Add Description page
toggle-corp/gaatha pull request #25
Opened 2021-07-02 06:06 UTC by barshathakuri

- Addresses xxxxxx (eg: #1)
- Depends on xxxxxx (eg: #1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

2021-07-05 07:29 UTC, subinasr requested changes

2021-07-05 07:29 UTC, subinasr commented on templates/works/detail.html
> +<link rel="stylesheet" type="text/css" href={% static 'css/workdetail.css' %}>
Why are we doing this? Multi-line code increases code readability. Can we please go back to making this mult-line?

2021-07-06 04:09 UTC, barshathakuri commented on templates/works/detail.html
> +<link rel="stylesheet" type="text/css" href={% static 'css/workdetail.css' %}>
Changed

2021-07-08 12:19 UTC, subinasr approved these changes

2021-07-08 12:19 UTC, merged