Add work item's picture and description
toggle-corp/gaatha pull request #27
Opened 2021-07-02 07:09 UTC by barshathakuri

- Addresses xxxxxx (eg: #1)
- Depends on xxxxxx (eg: #1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

2021-07-02 11:11 UTC, AdityaKhatri commented
@barshathakuri , could you write the PR description as specified in the template?

2021-07-05 07:22 UTC, subinasr requested changes

2021-07-05 07:22 UTC, subinasr commented on apps/work/models.py
> +        return self.description[:80] if self.description else self.image.url
Why are we doing this?

2021-07-05 07:22 UTC, subinasr commented on stylesheets/_dimens.scss
> +$width-content: calc(100vw - 405px);
Just asking a question here, what is 405px? Is it the width of the navbar?

2021-07-08 13:13 UTC, merged